"""empty message

Revision ID: 3acfa1f8cc7c
Revises: 4b6b032e0ab8
Create Date: 2024-03-07 12:46:00.806557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acfa1f8cc7c'
down_revision = '4b6b032e0ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('car_id', sa.String(), nullable=False),
    sa.Column('car_make', sa.String(length=300), nullable=False),
    sa.Column('car_body_type', sa.String(length=300), nullable=True),
    sa.Column('car_price', sa.String(length=100), nullable=False),
    sa.Column('car_year', sa.String(length=4), nullable=True),
    sa.Column('car_model', sa.String(length=300), nullable=False),
    sa.Column('car_fuel_type', sa.String(length=300), nullable=True),
    sa.Column('car_user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['car_user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('car_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
